language: php

php:
  - 7.3

addons:
  chrome: stable

services:
  - mysql

notifications:
  email: false

install:
  - cp .env.testing .env
  - travis_retry composer update --no-interaction
  - travis_retry composer install --no-interaction --prefer-dist
  - php artisan key:generate
  - php artisan dusk:chrome-driver

before_install:
  - mysql -e 'CREATE DATABASE exampletest;'

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve --no-reload &

script:
  - php artisan dusk
  - vendor/bin/phpunit
