name: PHP Code Sniffer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
          with:
            php-version: '7.3'
        - name: Install dependencies
          run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        - name: PHPCS check
          run: phpcs phpcs --standard=phpcs.xml app
